service: terraform-prac

app: terraform-prac-app
org: collinlshelby

plugins:
  - serverless-offline
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - http:
          path: helloworld
          method: get
          cors: true